# Generated by Django 3.0.3 on 2020-02-17 16:59

from django.db import migrations
from django.core.management import call_command

class Migration(migrations.Migration):

	def forwards(apps, schema_editor):
		call_command("loaddata", "categories.json")
		call_command("loaddata", "courses.json")

	dependencies = [
        ('studies', '0001_initial'),
    ]

	operations = [
		migrations.RunPython(forwards),
    ]
