# Generated by Django 3.0.3 on 2020-02-17 16:59

from django.db import migrations
from django.core.management import call_command

class Migration(migrations.Migration):

	def forwards(apps, schema_editor):
		call_command("loaddata", "languages.json")
		call_command("loaddata", "languages-translations.json")
		call_command("loaddata", "countries.json")
		call_command("loaddata", "countries-translations.json")
		# call_command("loaddata", "street-types.json")
		# call_command("loaddata", "street-types-translations.json")

	dependencies = [
        ('location', '0001_initial'),
    ]

	operations = [
		migrations.RunPython(forwards),
    ]
